const USER_STAGE = {
  ENTERED: 0,
  JOINED_TO_ROOM: 1,
  WAITING_FOR_NAME: 2,
  WAITING_FOR_DESCRIPTION: 3,
  WAITING_FOR_PHOTO: 4,
  WAITING_FOR_DRAW: 5,
  READY: 7,
  CONFIRM: 8
}

module.exports = {
  USER_STAGE: USER_STAGE,
}
